// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifmrpxcnhebocyvcbcpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmbXJweGNuaGVib2N5dmNiY3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTA3MDAsImV4cCI6MjA1OTYyNjcwMH0.0-31o_oJs04y9vpErCT1NT0LsibNA-PdfK8wrkCUNZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);